### ISSUE TITLE
Add model to PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by edmolima** [edmolima/awesome-backend-for-frontend#2]
Add a PULL_REQUEST_TEMPLATE template that you believe is relevant to this project

**Comment by edmolima** [comment]
@SergioJrDev claro. A idéia aqui é ser uma curadoria, então é importante a gente ter respostas para:

- É uma correção ou adição de algo novo?
- Qual categoria você quer adicionar? (video, link posts, podcasts e etc).

Pode adicionar algo que você considera relevante. Mas apenas isso já é suficiente.

**Comment by SergioJrDev** [comment]
PR aberta, caso tenha mais perguntas para colocar, só me avisar.
https://github.com/edmolima/awesome-backend-for-frontend/pull/5

**Comment by edmolima** [comment]
Valeu @SergioJrDev !
